apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-0.postgres.default.svc.cluster.local:5432/oris3
  SPRING_DATASOURCE_USERNAME: postgres
  FILE_UPLOAD_DIR: /app/uploads